### ISSUE TITLE
Spotifypie

### ISSUE THREAD

**Issue by konstantinlob** [konstantinlob/What-am-I-listening-to#14]
This component shows your favorite Spotify genres in the form of a pie chart.

**Comment by markus-gx** [comment]
If you want you can assign this to me too :)

**Comment by JuliusJaenchen** [comment]
We haven't had the time to create a Figma design for this one yet, sorry.
If you're still interested, you can also whip something up yourself :). We would probably base the design on this:
![image](https://user-images.githubusercontent.com/48837000/193410517-f093d26d-0c6f-4039-a2a6-24b6696ae627.png)
Otherwise, we might get around to designing it later this week.

Furthermore, we don't have much  Spotify-API request infrastructure yet. An initial static-data implementation might therefore be practical.
